version: '3.8'

services:
  node_exercises:
    build: .
    container_name: curso-node
    ports:
      - "8080:8080"  # Exponer Node en el puerto 8080
    volumes:
      - ./:/app                    # Monta todas las carpetas dentro de Capitulos en /app
    working_dir: /app
    stdin_open: true
    tty: true
    networks:
      - curso-network
  db:
    image: mysql/mysql-server:8.0
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: mydatabase
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    volumes:
      - ./mysql:/var/lib/mysql
      - ./Node/07_REST-SERVER/schema.sql:/docker-entrypoint-initdb.d/schema.sql
    ports:
      - "3306:3306"
    networks:
      - curso-network
  
networks:
  curso-network:
    driver: bridge  