version: '3'


services:

  nest:
    build: .
    container_name: nest_container
    ports:
      - "3000:3000"
    volumes:
      - ./:/app
    working_dir: /app
    stdin_open: true
    tty: true
    networks:
      - curso-network
  db:
    image: postgres:14.3
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: MySecr3tPassWord@as2
      POSTGRES_DB: postgres
    container_name: teslodb
    volumes:
      - ./postgres:/var/lib/postgresql/data
    networks:
      - curso-network

networks:
  curso-network:
    external: true

