version: "3.8"

services:
  curso-vue:
    build: .
    container_name: curso-vue
    ports:
      - "5173:5173"
    volumes:
      - ./:/app
    working_dir: /app
    stdin_open: true
    tty: true
    networks:
      - curso-network

networks:
  curso-network:
    name: curso-network
